In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline


In [11]:
data = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/flags/flag.data',names=names)

In [23]:
names=['name',
    'landmass',
   'zone',
    'area',
    'population',
    'language',
    'religion' ,
    'bars',    
   'stripes',  
   'colours', 
   'red',     
   'green',    
   'blue',     
   'gold',    
   'white',   
   'black',    
   'orange',  
   'mainhue',  
   'circles', 
   'crosses',  
   'saltires', 
   'quarters',
   'sunstars', 
   'crescent', 
   'triangle', 
   'icon',     
  'animate',  
    'text',     
   'topleft',  
   'botright',]

In [1]:
data.head()

NameError: name 'data' is not defined

In [43]:
orden=['name',
    'landmass',
   'zone',
    'area',
    'population',
    'language',
    'bars',    
   'stripes',  
   'colours', 
   'red',     
   'green',    
   'blue',     
   'gold',    
   'white',   
   'black',    
   'orange',  
   'mainhue',  
   'circles', 
   'crosses',  
   'saltires', 
   'quarters',
   'sunstars', 
   'crescent', 
   'triangle', 
   'icon',     
  'animate',  
    'text',     
   'topleft',  
   'botright',]

In [44]:
data=data[orden]

In [26]:
data.head()

name  landmass  zone  area  population  language  bars  stripes  \
0     Afghanistan         5     1   648          16        10     0        3   
1         Albania         3     1    29           3         6     0        0   
2         Algeria         4     1  2388          20         8     2        0   
3  American-Samoa         6     3     0           0         1     0        0   
4         Andorra         3     1     0           0         6     3        0   

   colours  red    ...     quarters  sunstars  crescent  triangle  icon  \
0        5    1    ...            0         1         0         0     1   
1        3    1    ...            0         1         0         0     0   
2        3    1    ...            0         1         1         0     0   
3        5    1    ...            0         0         0         1     1   
4        3    1    ...            0         0         0         0     0   

   animate text  topleft  botright  religion  
0        0    0    black     green         2  
1        1    0      red       red         6  
2        0    0    green     white         2  
3        1    0     blue       red         1  
4        0    0     blue       red         0  

[5 rows x 30 columns]

In [13]:
x=data.iloc[:,:-1]

In [14]:
y=data.iloc[:,-1]

In [15]:
x.isnull().values.any()


False

In [16]:
x.empty

False

In [18]:
from sklearn.preprocessing import Normalizer,LabelEncoder


In [20]:
nor_x = LabelEncoder
nor_y = LabelEncoder

In [31]:
x = pd.get_dummies(x)
y = pd.get_dummies(y)

In [22]:
from sklearn.linear_model import LinearRegression

In [28]:
lr = LinearRegression()

In [32]:
lr.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [48]:
lr.predict(x)

array([[-2.38697950e-15,  1.39332990e-14, -1.90125693e-15, ...,
        -6.49480469e-15,  1.45161660e-14,  8.88178420e-15],
       [ 1.72847847e-13,  9.07940390e-13,  1.25871535e-14, ...,
        -2.02476924e-14,  1.00000000e+00,  3.63736818e-13],
       [-1.65839564e-14,  1.74804615e-13, -2.17603713e-14, ...,
        -7.58559882e-14,  3.95156130e-13,  1.00000000e+00],
       ...,
       [-5.12090370e-15,  1.25177646e-14, -3.19189120e-15, ...,
        -7.32747196e-15,  2.44526621e-14,  5.44009282e-15],
       [-1.48492330e-15, -1.92623695e-14,  1.00000000e+00, ...,
        -4.87110352e-15,  3.90243393e-14,  6.93889390e-16],
       [ 5.66213743e-15, -2.11775042e-14,  2.88657986e-15, ...,
         7.53563878e-15, -1.09356968e-14, -1.16295862e-14]])

In [37]:
target = data['religion']


In [38]:
lr.score(x,y)

1.0

In [39]:
y = target

In [50]:
lr.coef_

array([[ 1.68743804e-03, -2.11137851e-03,  6.40749250e-07, ...,
        -4.72030567e-02, -1.25255123e-01, -1.19433259e-01],
       [-2.20662427e-03,  3.94942603e-04,  1.74701068e-07, ...,
        -6.25266164e-02, -1.40470938e-01, -1.33042087e-01],
       [ 9.97393796e-04,  7.99382366e-05,  1.80651451e-07, ...,
        -5.00425326e-02, -8.38725426e-02, -7.48233894e-02],
       ...,
       [ 2.75709474e-03,  1.90371484e-03, -4.15486606e-07, ...,
         4.02345855e-01, -6.24115313e-02, -6.11557951e-02],
       [-1.75962650e-03,  1.39762050e-04,  2.63229371e-07, ...,
        -6.24115313e-02,  8.28226919e-01, -1.44291139e-01],
       [-2.23681403e-03,  6.84078072e-04, -1.80501402e-07, ...,
        -6.11557951e-02, -1.44291139e-01,  7.86420186e-01]])

In [51]:
lr.intercept_

array([0.10892504, 0.16220533, 0.10168138, 0.14879548, 0.13606359,
       0.06254113, 0.14547481, 0.13431324])

In [52]:
lr.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)